version: '3.8'
services:
  postgres:
    container_name: bforbank-postgres
    restart: unless-stopped
    image: postgres:15.7
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-moneypot}
      PGDATA: /data/postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    networks:
      - postgres

networks:
  postgres:
    driver: bridge

volumes:
  postgres: